services:
  server:
    build:
      context: .
      target: build
    volumes:
      - ./:/server
      - /server/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run dev
